import React, { useEffect, useState } from "react";
import axios from "../../Fetch/axios";
import requests from "../../Fetch/requests";
import "./Banner.css";

function Banner() {
  const [movie, setMovie] = useState([]);

  useEffect(() => {
    async function fetchData() {
      const request = await axios.get(requests.fetchNetflixOriginals);
      setMovie(
        request.data.results[
          Math.floor(Math.random() * request.data.results.length - 1)
        ]
      );
      return request;
    }
    fetchData();
  }, []);

  console.log(movie);

  function truncate(str, n) {
    return str?.length > n ? str.substr(0, n - 1) + "..." : str;
  }

  return (
    <header
      className="banner"
      style={{
        backgroundSize: "cover", // sets the background size to "cover"
        backgroundImage: `url("https://image.tmdb.org/t/p/original/${movie?.backdrop_path}")`, // sets the background image to a URL generated by a template literal that interpolates the backdrop_path property of the movie object
        backgroundPosition: "center center", // sets the background position to the center of the element
      }}
    >
      <div className="banner_contents">
        <h1 classname="banner_title">
          {movie?.title || movie?.name || movie?.original_name}
        </h1>

        <div className="banner_buttons">
          <button classNme="banner_button"> Play</button>
          <button classNme="banner_button"> My List</button>
        </div>

        <h1 classname="banner_description">{truncate(movie?.overview, 150)}</h1>
      </div>

      <div className="banner--fadeBottom" />
    </header>
  );
}

export default Banner;
